### ISSUE TITLE
Why only "Pearson's" method for correlation? 

### ISSUE THREAD

**Issue by gd047** [alastairrushworth/inspectdf#11]
I liked very much your correlation plot!
It would be nice to have the option of choosing alternative methods for calculating the correlation in `inspect_cor` (e.g "spearman" and "kendall" )

**Comment by alastairrushworth** [comment]
Hi @gd047, the short answer is that stat tests for comparing pairs of spearman & kendal require a different type of test - maybe a bootstrap.  That's not necessarily a huge problem & I agree it would be useful.  I'll add this to the list of features to add to the next release.  Thanks!

**Comment by gd047** [comment]
Just for the record, I use corr.test {psych} and `holm's` adjustment for multiple tests.

**Comment by alastairrushworth** [comment]
Hi @gd047, a wee update.  As of v0.0.4 (now on CRAN), you can request Kendall or Spearman correlation using

`df %>% inspect_cor(method = "kendal")`

For now, only the point estimates are returned or plotted.  Tests and confidence intervals are not implemented yet, I'll leave this issue open until that is added.

**Comment by alastairrushworth** [comment]
Intervals and tests (based on normal approximation to the Fisher z-transform) for Kendall and Spearman correlations have been added to the development version.  This will be rolled into the next CRAN release.  Thanks again!
