### ISSUE TITLE
"" values causing error?

### ISSUE THREAD

**Issue by mwswenson** [alastairrushworth/inspectdf#12]
It appears that "" values cause the following error:

Error in if (tg$gp$fontsize < x$min.size) return() : 
  missing value where TRUE/FALSE needed

I am able to update all of "" to "DATA NOT PROVIDED" and it runs fine.

Thanks for the great tool!

**Comment by alastairrushworth** [comment]
Thanks for the report @mwswenson.  I'm on it!

**Comment by alastairrushworth** [comment]
Hi @mwswenson there is now a fix for this on the github version of the package & will appear in a week or so on CRAN.  Thanks again for the issue!
