### ISSUE TITLE
Unsorted plots?

### ISSUE THREAD

**Issue by biodavidjm** [alastairrushworth/inspectdf#15]
Is there a way of not sorting the plots when enabling the option `show_plot = TRUE`? It would be really useful.

Thanks and congrats on the package!

**Comment by alastairrushworth** [comment]
Hi @biodavidjm thanks for your message.  

Firstly, the `show_plot = TRUE` option is deprecated and is going to be removed from a future release of the package.  If you aren't seeing a warning when you use the option, then you may be using an older version of the package - if so I'd recommend updating.

That being said, it may be that the `show_plot()` function doesn't give you what you want.  Can you give a bit more detail (ideally an example too) about what you'd like to see?

Thanks!

**Comment by biodavidjm** [comment]
You are right, in fact, I was using the functions as recommended, i.e.,

```
inspectdf::inspect_na(df) %>% show_plot()
```

but before sending you the question I explored the help and noticed that I could also use the `show_plot` as an argument inside that function (and yes, I got the soon deprecated message)

Coming back to your question, the sorted barplot is useful, but having the option of an unsorted barplot would be very useful as well. For example, some data frames might have a very well defined structure and particular column order well-known by a particular community of users. And just plotting the barplot keeping the order of the original data frame would be easy to illustrate what columns are coming with a large number of NA values (if using the `inspect_na` function). In summary, to have an extra argument `sort_barplot = FALSE` would be helpful, i.e.

```
inspectdf::inspect_na(df) %>% show_plot(sort_barplot = FALSE)
```

... leaving `TRUE` as default

**Comment by alastairrushworth** [comment]
Hi @biodavidjm 

Ok I see what you mean.  I think this might be possible just by adding an `arrange()` after the `inspect_` statement:

```
library(inspectdf)
library(dplyr)

starwars %>% 
  inspect_na() %>% 
  arrange(match(col_name, colnames(starwars))) %>%
  show_plot()
```

Does that help, or are you looking at something more complex than this?

**Comment by biodavidjm** [comment]
Yes! it does the trick! thanks a lot
