### ISSUE TITLE
inspect_num breaks when column is all NAs

### ISSUE THREAD

**Issue by ryanatanner** [alastairrushworth/inspectdf#18]
Thanks for the great package; I noticed that the `inspect_num` function hits an error when `hist` gets a column with exclusively NAs, like this. 

    inspect_num(data.frame(a = 1:100, b = rep(NA_real_, 100)))

Here's the error I'm seeing:

    Error in hist.default(df_num[[breaks_tbl$col_name[i]]], plot = FALSE,  :    character(0)
    In addition: Warning messages: 
    1: In min(value, na.rm = T) :   no non-missing arguments to min; returning Inf 
    2: In max(value, na.rm = T) :   no non-missing arguments to max; returning -Inf

Cheers!

**Comment by alastairrushworth** [comment]
Thanks so much for the report @ryanatanner!  This has now been fixed in the dev version.  I'll get an update to the CRAN version shortly.
