### ISSUE TITLE
inspect_imb fails on iris dataaset

### ISSUE THREAD

**Issue by doug-friedman** [alastairrushworth/inspectdf#19]
I'm not quite sure why, but `inspect_imb` fails a lot for me with the same error. See below for a simple example.

```r
library(inspectdf)
inspect_imb(iris)
# Error in sapply(df_cat_fact, are_lvls_unq) : 
#  object 'df_cat_fact' not found
```

**Comment by alastairrushworth** [comment]
Hi @doug-friedman, thanks for reporting this.  This was a bug, which has now been fixed in the github version.  Please let me known if you have any further issues!
