### ISSUE TITLE
Suggestion: rotating `inspect_imb()` plot

### ISSUE THREAD

**Issue by RoelVerbelen** [alastairrushworth/inspectdf#25]
For scalability, when working with data with many columns, it would be great if there would be an option to rotate the `inspect_imb()` plot. Currently, the best way to achieve this is by using `ggplot2::coord_flip()`, but that messes up the label positioning (vertical and overlapping) and it's not possible to reverse the levels on the discrete y-axis.

``` r
# Load 
library(inspectdf)
library(dplyr)
library(ggplot2)

# Imbalance plot
inspect_imb(starwars) %>% 
  show_plot()
```

![](https://i.imgur.com/ypuOayG.png)

``` r

# Rotate
inspect_imb(starwars) %>% 
  show_plot() + 
  coord_flip()
```

![](https://i.imgur.com/u8QGsyc.png)

<sup>Created on 2020-02-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alastairrushworth** [comment]
Hi @RoelVerbelen - this should now work where the output of the `inspect_` function is a single df summary (it's a bit more work to get the text annotation right for comparison-type plots.  

For example:

```
library(inspectdf)
library(dplyr)
library(ggplot2)

inspect_imb(starwars) %>% 
  show_plot(label_angle = 0) + 
  coord_flip()
```

Note that the `label_angle` argument is required to return the labels to their unrotated state (by default, they are now rotated by 90 degrees).  This is available in the GH version now, and will be part of the next cran release soon.

Thanks again!

**Comment by RoelVerbelen** [comment]
Thanks Alastair for incorporating these suggestions!
