### ISSUE TITLE
change white color for last (or second) factor.

### ISSUE THREAD

**Issue by ivokwee** [alastairrushworth/inspectdf#32]
Hi. The color for the last factor is white but for especially for groups with two factors the first one is coloured but the second is white. It would be nice the second group is not white but a lighter shade of the first color. Meaning the colorpallete should not go until white. Thanks.

**Comment by alastairrushworth** [comment]
Hi @ivokwee thanks for getting in touch.  Could you please provide a reprex so I can understand better the issue you are reporting?

**Comment by alastairrushworth** [comment]
Hey @ivokwee, this should be fixed in the development version of `inspectdf`.  It will be included in the next cran release.  thanks again for the issue!
