### ISSUE TITLE
inspect_num: inconsistent binning of numerical variables in comparisons

### ISSUE THREAD

**Issue by RoelVerbelen** [alastairrushworth/inspectdf#40]
Hi Alastair, 

I like the idea and the visual, but the binning implementation seems wrong:

``` r
library(inspectdf)

data1 <- data.frame(x = c(rep(0, 250), rep(1, 250)))
data2 <- data.frame(x = c(rep(0, 230), rep(1, 270)))

show_plot(inspect_num(data1, data2))
```

![](https://i.imgur.com/9x6mjf8.png)

<sup>Created on 2021-06-09 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

It even occurs for identical data:

```r
show_plot(inspect_num(data1, data1))
```

**Comment by alastairrushworth** [comment]
Thanks for reporting this @RoelVerbelen !  this should now be fixed on the dev version of the package.  I'll roll this into the next CRAN update within the week.  Cheers!
