### ISSUE TITLE
inspect_num %>% show_plot fails on grouped dataframe with Error object 'mid' not found 

### ISSUE THREAD

**Issue by cregouby** [alastairrushworth/inspectdf#41]
Hello, 

`show_plot()` is failing to render a plot out of `inspect_num()` when the dataset is grouped.
The `mid` object in the code at [plot_num.R#L173](https://github.com/alastairrushworth/inspectdf/blob/bdf2af6885441049a4c5c8107325708d4330fafe/R/plot_num.R#L173) is actually not defined

# ReprEx
``` r
library(dplyr)
library(inspectdf)
mtcars %>% dplyr::group_by(am) %>% inspect_num() %>% show_plot()
#> Error in layer(data = data, mapping = mapping, stat = stat, geom = GeomBar, : object 'mid' not found
```

<sup>Created on 2021-08-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by alastairrushworth** [comment]
thanks for this PR, and for raising the issue.  I hadn't implemented groupby-visualisations for inspect_num at this time, but I've now added a new (experimental for now) graphic that does this.  the new graphic is a bit different to the paired plots, but it resolves this issue.  Thanks again 😊
