### ISSUE TITLE
Automatic sizing of text

### ISSUE THREAD

**Issue by wilkox** [alastairrushworth/inspectdf#5]
Hi @alastairrushworth, thanks for the great package!

Would you be interested in a pull request that adds automatic text sizing to the plots?

`plot_cat()` for `mpg` currently looks like this:

![](https://i.imgur.com/kNn2x7V.png)

If `plot_cat()` instead used `geom_fit_text()` from my package [ggfittext](https://github.com/wilkox/ggfittext), the text could be automatically sized like this:

![](https://i.imgur.com/W8uQXJJ.png)

`geom_fit_text()` supports options for hiding text below a minimum size etc. that could be passed on through `show_plot()`.

If you think this would be a worthwhile addition I can submit a pull request that adds `geom_fit_text()` to all the `plot_*()` functions.

**Comment by alastairrushworth** [comment]
Hi @wilkox, this is a great suggestion, if you have time to make a PR that would be terrific!  As you can probably see, I’ve added some dirty hacks to get text sizing to work in some of the plots, your ggfittext package is a much more elegant solution to this!  

Thanks for your package and for the suggestion!
