### ISSUE TITLE
show_plot(x) displays empty histograms for DF num columns

### ISSUE THREAD

**Issue by sfd99** [alastairrushworth/inspectdf#7]
**_Hi Alastair,_**

**inspectdf** Pkg is Great!.

This show_plot() example
_works fine_:
> x <- inspect_num(starwars)
> show_plot(x)

But... this ex. does not work:
_(it just shows 4 empty histograms...)_
> x <- inspect_num(iris)
> show_plot(x)

Neither does this example:
_(it just shows 11 empty histograms...)_
> x <- inspect_num(mtcars)
> show_plot(x)

Help! What am I missing?.
**SFd99
San Francisco
_Ubuntu Linux,  R 351,  Rstudio 1.1.463, 
inspectdf PKG ver 0.0.2 (installed from CRAN)_
----**

**Comment by sfd99** [comment]
*

**Comment by alastairrushworth** [comment]
Hi @sfd99 

Thanks for the report!  I think this could be an issue in the CRAN version of the package, the development version has a few recent bug fixes for `inspect_num()` (an update will go to CRAN shortly).  Could you try installing from github and let me know whether you still see the problem?

`library(devtools)`
`install_github("alastairrushworth/inspectdf")`

Thanks!

**Comment by sfd99** [comment]
Ok! 
in GIT (development) version
**it all works 100% fine**. 

 Thanks  Alastair! :-)
(love the **inspectdf** package.
very, very useful!).
