### ISSUE TITLE
installation non zero exit status

### ISSUE THREAD

**Issue by stevecrawshaw** [alastairrushworth/inspectdf#8]
Hi
This is on my work PC.

compilation terminated.
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:215: RcppExports.o] Error 1
ERROR: compilation failed for package 'inspectdf'
* removing 'C:/Program Files/R/R-3.5.1/library/inspectdf'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/brplsec/AppData/Local/Temp/RtmpW8a2Gn/file2428705a7d95/inspectdf_0.0.2.9000.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by alastairrushworth** [comment]
Hi @stevecrawshaw 

Could you paste the full result of `devtools::install_github('alastairrushworth/inspectdf')`?

At a glance, the issue looks similar to [this one](https://github.com/r-lib/devtools/issues/1863) but need more info to check.

Thanks!

**Comment by stevecrawshaw** [comment]
√  checking for file 'C:\Users\brplsec\AppData\Local\Temp\RtmpE9RJv3\remotes27e853066131\alastairrushworth-inspectdf-6132c28/DESCRIPTION' ...
-  preparing 'inspectdf': (547ms)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
   Warning in as.POSIXlt.POSIXct(x, tz) : unknown timezone 'GMT'
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'inspectdf_0.0.2.9000.tar.gz'
   
* installing *source* package 'inspectdf' ...
Warning in as.POSIXlt.POSIXct(x, tz) : unknown timezone 'GMT'
** libs
Warning: R include directory is empty -- perhaps need to install R-devel.rpm or similar
C:/RBuildTools/3.5/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-35~1.1/include" -DNDEBUG  -I"C:/Program Files/R/R-3.5.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
In file included from C:/Program Files/R/R-3.5.1/library/Rcpp/include/RcppCommon.h:29:0,
                 from C:/Program Files/R/R-3.5.1/library/Rcpp/include/Rcpp.h:27,
                 from RcppExports.cpp:4:
C:/Program Files/R/R-3.5.1/library/Rcpp/include/Rcpp/r/headers.h:63:15: fatal error: R.h: No such file or directory
 #include <R.h>
               ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-35~1.1/etc/i386/Makeconf:215: RcppExports.o] Error 1
ERROR: compilation failed for package 'inspectdf'
* removing 'C:/Program Files/R/R-3.5.1/library/inspectdf'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/brplsec/AppData/Local/Temp/RtmpE9RJv3/file27e87f6b4b08/inspectdf_0.0.2.9000.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

**Comment by alastairrushworth** [comment]
The key issue seems to be `C:/Program Files/R/R-3.5.1/library/Rcpp/include/Rcpp/r/headers.h:63:15: fatal error: R.h: No such file or directory` - the header files seem to be missing.  This is something to do with your R install rather than `inspectdf` itself.  You could try reinstalling `Rcpp` and see if that helps.

**Comment by stevecrawshaw** [comment]
Thanks for the response. I have tried reinstalling Rcpp to no avail. Unfortunately my ability to control the installation of R is limited by corporate policies, so for now I think I will have to do without inspectdf.

**Comment by alastairrushworth** [comment]
Yeah, sorry I couldn't be much help - I'm not sure I'd be able to advise what to try even if you could make changes to the install.  It could be worth putting a question up on SO - I noticed a few like this, though nothing identical.
